// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: articles.sql

package database

import (
	"context"
)

const getArticleCache = `-- name: GetArticleCache :one
SELECT post_id, source_url, final_url, markdown, title, author, site_name, published_at, fetched_at FROM article_cache
WHERE post_id = ? AND source_url = ?
`

type GetArticleCacheParams struct {
	PostID    int64
	SourceUrl string
}

func (q *Queries) GetArticleCache(ctx context.Context, arg GetArticleCacheParams) (ArticleCache, error) {
	row := q.db.QueryRowContext(ctx, getArticleCache, arg.PostID, arg.SourceUrl)
	var i ArticleCache
	err := row.Scan(
		&i.PostID,
		&i.SourceUrl,
		&i.FinalUrl,
		&i.Markdown,
		&i.Title,
		&i.Author,
		&i.SiteName,
		&i.PublishedAt,
		&i.FetchedAt,
	)
	return i, err
}

const upsertArticleCache = `-- name: UpsertArticleCache :one
INSERT INTO article_cache (
    post_id, source_url, final_url, markdown, title, author, site_name, published_at
)
SELECT id, link, ?, ?, ?, ?, ?, ?
FROM posts
WHERE id = ? AND link = ?
ON CONFLICT (post_id) DO UPDATE SET
    source_url = excluded.source_url,
    final_url = excluded.final_url,
    markdown = excluded.markdown,
    title = excluded.title,
    author = excluded.author,
    site_name = excluded.site_name,
    published_at = excluded.published_at,
    fetched_at = CURRENT_TIMESTAMP
RETURNING post_id, source_url, final_url, markdown, title, author, site_name, published_at, fetched_at
`

type UpsertArticleCacheParams struct {
	FinalUrl    string
	Markdown    string
	Title       string
	Author      string
	SiteName    string
	PublishedAt string
	ID          int64
	Link        string
}

func (q *Queries) UpsertArticleCache(ctx context.Context, arg UpsertArticleCacheParams) (ArticleCache, error) {
	row := q.db.QueryRowContext(ctx, upsertArticleCache,
		arg.FinalUrl,
		arg.Markdown,
		arg.Title,
		arg.Author,
		arg.SiteName,
		arg.PublishedAt,
		arg.ID,
		arg.Link,
	)
	var i ArticleCache
	err := row.Scan(
		&i.PostID,
		&i.SourceUrl,
		&i.FinalUrl,
		&i.Markdown,
		&i.Title,
		&i.Author,
		&i.SiteName,
		&i.PublishedAt,
		&i.FetchedAt,
	)
	return i, err
}
