// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: feeds.sql

package database

import (
	"context"
)

const countFeeds = `-- name: CountFeeds :one
SELECT COUNT(*)
FROM feeds
WHERE instr(unicode_lower(name), unicode_lower(CAST(?1 AS TEXT))) > 0
`

func (q *Queries) CountFeeds(ctx context.Context, search string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countFeeds, search)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createFeed = `-- name: CreateFeed :one
INSERT INTO feeds (
    name, url
) VALUES (
    ?, ?
) RETURNING id, created_at, updated_at, name, url, last_fetched_at
`

type CreateFeedParams struct {
	Name string
	Url  string
}

func (q *Queries) CreateFeed(ctx context.Context, arg CreateFeedParams) (Feed, error) {
	row := q.db.QueryRowContext(ctx, createFeed, arg.Name, arg.Url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.LastFetchedAt,
	)
	return i, err
}

const getFeedPosition = `-- name: GetFeedPosition :one
WITH target AS (
    SELECT feed.id, feed.created_at
    FROM feeds AS feed
    WHERE feed.id = ?2
)
SELECT COUNT(*)
FROM feeds, target
WHERE instr(unicode_lower(feeds.name), unicode_lower(CAST(?1 AS TEXT))) > 0
  AND (
      feeds.created_at < target.created_at
      OR (feeds.created_at = target.created_at AND feeds.id < target.id)
  )
`

type GetFeedPositionParams struct {
	Search string
	ID     int64
}

func (q *Queries) GetFeedPosition(ctx context.Context, arg GetFeedPositionParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, getFeedPosition, arg.Search, arg.ID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getFeedsForRefresh = `-- name: GetFeedsForRefresh :many
SELECT
    id, created_at, updated_at, name, url, last_fetched_at
FROM feeds
ORDER BY created_at, id
`

func (q *Queries) GetFeedsForRefresh(ctx context.Context) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getFeedsForRefresh)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Url,
			&i.LastFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeedsPage = `-- name: GetFeedsPage :many
SELECT
    id,
    created_at,
    updated_at,
    name,
    url,
    last_fetched_at
FROM feeds
WHERE instr(unicode_lower(name), unicode_lower(CAST(?1 AS TEXT))) > 0
ORDER BY created_at, id
LIMIT ?3 OFFSET ?2
`

type GetFeedsPageParams struct {
	Search string
	Offset int64
	Limit  int64
}

func (q *Queries) GetFeedsPage(ctx context.Context, arg GetFeedsPageParams) ([]Feed, error) {
	rows, err := q.db.QueryContext(ctx, getFeedsPage, arg.Search, arg.Offset, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Feed
	for rows.Next() {
		var i Feed
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Name,
			&i.Url,
			&i.LastFetchedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextFeedToFetch = `-- name: GetNextFeedToFetch :one
SELECT
    id, created_at, updated_at, name, url, last_fetched_at
FROM feeds
ORDER BY last_fetched_at ASC
LIMIT 1
`

func (q *Queries) GetNextFeedToFetch(ctx context.Context) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getNextFeedToFetch)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.LastFetchedAt,
	)
	return i, err
}

const markFeedAsFetched = `-- name: MarkFeedAsFetched :execrows
UPDATE feeds
SET last_fetched_at = CURRENT_TIMESTAMP,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) MarkFeedAsFetched(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.ExecContext(ctx, markFeedAsFetched, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
