// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type Feed struct {
	ID            int64
	CreatedAt     string
	UpdatedAt     string
	Name          string
	Url           string
	LastFetchedAt sql.NullString
}

type User struct {
	ID        int64
	CreatedAt string
	UpdatedAt string
	Username  string
}
