// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package database

import (
	"database/sql"
)

type Feed struct {
	ID            int64
	CreatedAt     string
	UpdatedAt     string
	Name          string
	Url           string
	LastFetchedAt sql.NullString
}

type Post struct {
	ID              int64
	FeedID          int64
	IdentityKey     string
	CreatedAt       string
	UpdatedAt       string
	SourceID        string
	GuidIsPermalink sql.NullInt64
	Title           string
	Link            string
	Content         string
	ContentKind     string
	PublishedRaw    string
	PublishedAt     sql.NullString
	UpdatedRaw      string
	SourceUpdatedAt sql.NullString
}

type User struct {
	ID        int64
	CreatedAt string
	UpdatedAt string
	Username  string
}
