// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: posts.sql

package database

import (
	"context"
	"database/sql"
)

const getPost = `-- name: GetPost :one
SELECT id, feed_id, identity_key, created_at, updated_at, source_id, guid_is_permalink, title, link, content, content_kind, published_raw, published_at, updated_raw, source_updated_at FROM posts
WHERE id = ?
`

func (q *Queries) GetPost(ctx context.Context, id int64) (Post, error) {
	row := q.db.QueryRowContext(ctx, getPost, id)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.IdentityKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceID,
		&i.GuidIsPermalink,
		&i.Title,
		&i.Link,
		&i.Content,
		&i.ContentKind,
		&i.PublishedRaw,
		&i.PublishedAt,
		&i.UpdatedRaw,
		&i.SourceUpdatedAt,
	)
	return i, err
}

const getPostsByFeed = `-- name: GetPostsByFeed :many
SELECT id, feed_id, identity_key, created_at, updated_at, source_id, guid_is_permalink, title, link, content, content_kind, published_raw, published_at, updated_raw, source_updated_at FROM posts
WHERE feed_id = ?
ORDER BY id DESC
`

func (q *Queries) GetPostsByFeed(ctx context.Context, feedID int64) ([]Post, error) {
	rows, err := q.db.QueryContext(ctx, getPostsByFeed, feedID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Post
	for rows.Next() {
		var i Post
		if err := rows.Scan(
			&i.ID,
			&i.FeedID,
			&i.IdentityKey,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SourceID,
			&i.GuidIsPermalink,
			&i.Title,
			&i.Link,
			&i.Content,
			&i.ContentKind,
			&i.PublishedRaw,
			&i.PublishedAt,
			&i.UpdatedRaw,
			&i.SourceUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertPost = `-- name: UpsertPost :one
INSERT INTO posts (
    feed_id,
    identity_key,
    source_id,
    guid_is_permalink,
    title,
    link,
    content,
    content_kind,
    published_raw,
    published_at,
    updated_raw,
    source_updated_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?
)
ON CONFLICT (feed_id, identity_key) DO UPDATE SET
    source_id = excluded.source_id,
    guid_is_permalink = excluded.guid_is_permalink,
    title = excluded.title,
    link = excluded.link,
    content = excluded.content,
    content_kind = excluded.content_kind,
    published_raw = excluded.published_raw,
    published_at = excluded.published_at,
    updated_raw = excluded.updated_raw,
    source_updated_at = excluded.source_updated_at,
    updated_at = CURRENT_TIMESTAMP
RETURNING id, feed_id, identity_key, created_at, updated_at, source_id, guid_is_permalink, title, link, content, content_kind, published_raw, published_at, updated_raw, source_updated_at
`

type UpsertPostParams struct {
	FeedID          int64
	IdentityKey     string
	SourceID        string
	GuidIsPermalink sql.NullInt64
	Title           string
	Link            string
	Content         string
	ContentKind     string
	PublishedRaw    string
	PublishedAt     sql.NullString
	UpdatedRaw      string
	SourceUpdatedAt sql.NullString
}

func (q *Queries) UpsertPost(ctx context.Context, arg UpsertPostParams) (Post, error) {
	row := q.db.QueryRowContext(ctx, upsertPost,
		arg.FeedID,
		arg.IdentityKey,
		arg.SourceID,
		arg.GuidIsPermalink,
		arg.Title,
		arg.Link,
		arg.Content,
		arg.ContentKind,
		arg.PublishedRaw,
		arg.PublishedAt,
		arg.UpdatedRaw,
		arg.SourceUpdatedAt,
	)
	var i Post
	err := row.Scan(
		&i.ID,
		&i.FeedID,
		&i.IdentityKey,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SourceID,
		&i.GuidIsPermalink,
		&i.Title,
		&i.Link,
		&i.Content,
		&i.ContentKind,
		&i.PublishedRaw,
		&i.PublishedAt,
		&i.UpdatedRaw,
		&i.SourceUpdatedAt,
	)
	return i, err
}
